config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	root 'top#show'
  	post 'users/index'
	 resources :books
	 resources :users, except:[:edit,:update,:destroy]
	 resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	enum category: {日本:1, 海外:2}
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def require_user_logged_in
		unless logged_in?
			redirect_to users_path
		end
	end
	def current_user
		@current_user ||= User.find_by(id: sesstion[:user_id])
	end

	def logged_in?
		!!current_user
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end

  def new
  	@book = Book.new
  end

  def create
  	book = Book.new(book_params)
  	book.save
  	redirect_to books_path
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	book = Book.find(params[:id])
  	book.update(book_params)
  	redirect_to books_path
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private
  def book_params
        params.require(:book).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    name     = params[:session][:name]
    password = params[:session][:password]
    if login(name, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id]=nil
    flash[:success]="ログアウトしました"
    redirect_to root_path
  end

  private

  def login(name , password)
    @user=User.find(params[:id])
    if @user && @user.authenticate(password)

      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = 'ユーザを登録しました。'
  		redirect_to @user
  	else
  		flash.now[:danger] = 'ユーザー登録に失敗しました'
  		render :new
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>

<h4>title</h4>
<%= form.text_field :title %>

<h4>body</h4>
<%= form.text_field :body %>

<h4>category</h4>
<%= form.radio_button :category, :日本 %>
<%= form.label :category, "日本"%>

<%= form.radio_button :category, :海外 %>
<%= form.label :category, "海外"%><br>

<%= form.submit '投稿' %>

<% end %>

app/views/books/edit.html.erb
<h1>編集</h1>
<%= render 'books/form', book: @book %>

<%= link_to "戻る", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<p>現在の投稿数は<%= @books.count %></p>
	<% @books.each do |book| %>
	 <table>
	 	<tbody>
	 		<tr>
	 			<th>book</th>
	 			<th>body</th>
	 			<th>category</th>
	 		</tr>
	 		<tr>
	 			<td><%= book.title %></td>
	 			<td><%= book.body %></td>
	 			<td><%= book.category %></td>
	 			<td><%= link_to "show", book_path(book.id) %></td>
	 			<td><%= link_to "edit", edit_book_path(book) %></td>
	 			<td><%= link_to "destroy", book_path(book), method: :delete %></td>
	 		</tr>
	 	</tbody>
	 </table>
	<% end %>

<h1>新規投稿</h1>
<%= render 'books/form',book: @book %>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booklife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/show.html.erb
<h1>Top#show</h1>
<p>Find me in app/views/top/show.html.erb</p>

app/views/users/new.html.erb
<h1>ユーザー新規登録</h1>
<p>
<%= form_for(@user) do |f| %>
</p>
<div class="form-group">
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :email, 'Email' %>
    <%= f.email_field :email, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :password_confirmation, 'Confirmation' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>
<P>
<%= f.submit '新規登録', class: 'btn btn-primary btn-block' %>

<% end %>

app/views/users/show.html.erb
<h3 class="panel-title"><%= @user.name %></h3>